### ISSUE TITLE
Question. Does this library support non inactive client like CLI

### ISSUE THREAD

**Issue by linearregression** [coreos/go-oidc#147]
non interactive client may not be able to do redirect and any steps that involve manual entry.
Doesthis library support non  interactive client like CLI?

**Comment by ericchiang** [comment]
This package is un-opinionated about redirects or oauth2 flows. It basically is just used to verify and parse OpenID Connect ID token.

Since this isn't a bug report, I'm going to close this. If there's a provider that implements a specific device flow this client doesn't support, feel free to open another issue.
