### ISSUE TITLE
Verify should check the Authorizing party claim

### ISSUE THREAD

**Issue by JoelSpeed** [coreos/go-oidc#158]
I am trying to implement [Cross client trust](https://github.com/coreos/dex/blob/master/Documentation/custom-scopes-claims-clients.md#cross-client-trust-and-authorized-party) to enable an application to request authentication on behalf of another.

This then sets the `azp` claim of the token that is returned to the client id of the application that made the request. 

Currently the verify code only checks the `ClientID` of the token contains the `ClientID` from the config. I believe it should actually check that either the `ClientID` of the token contains this or it should check for an `azp` claim and see if this matches the `ClientID` from the config. I believe this could be achieved by modifying the code below 

https://github.com/coreos/go-oidc/blob/a4973d9a4225417aecf5d450a9522f00c1f7130f/verify.go#L164-L166

**Comment by ericchiang** [comment]
Since most apps care about audiences the verifier checks that. If you're using an ID token as a session cookie, your server would want to verify that a token is issued for a trusted client.

My take on cross client trust is that it lets a client issue tokens on behalf of another client. Your server would still want to verify the audience field, and the authorizing party acts as an auditing mechanism.

That's the motivation of the current code. I'm not sure when it'd be prudent to enforce a specific value of the `azp` field. That seems opposite to the point of cross client trust. It's possible that I've misread the spec though.

**Comment by JoelSpeed** [comment]
I've re-read the spec and realised that in fact Dex was returning invalid tokens, hence they weren't passing the verify. 

When using the cross client trust, Dex was only passing back the `peerID` and not including the `clientID` in the `aud` field, making the token invalid. There's a better description of the problem in this [issue](https://github.com/coreos/dex/issues/1087). But it has been fixed now, just need to wait for the next release.
