### ISSUE TITLE
Thread-safety

### ISSUE THREAD

**Issue by andy-miracl** [coreos/go-oidc#174]
Hi,

Is it safe to call functions on a single instance of `oidc.Client` from multiple goroutines?

Thanks

Andy

**Comment by ericchiang** [comment]
There is no oidc.Client, but if you mean oidc.IDTokenVerifier, yes it's
safe to call Verify() concurrently. The examples show specific functions
being used inside a HTTP handler, which should give a good intuition about
what's expected to be called within a gorouine.

**Comment by andy-miracl** [comment]
Thanks, but to be clear, I mean https://github.com/coreos/go-oidc/blob/master/oidc/client.go, which has :

```
type Client struct {
	httpClient     phttp.Client
	providerConfig *providerConfigRepo
	credentials    ClientCredentials
	redirectURL    string
	scope          []string
	keySet         key.PublicKeySet
	providerSyncer *ProviderConfigSyncer

	keySetSyncMutex sync.RWMutex
	lastKeySetSync  time.Time
}
```

**Comment by ericchiang** [comment]
Ah. The v1 and master branches are deprecated in favor of the v2 branch.

https://github.com/coreos/go-oidc/blob/master/oidc/doc.go

Please use the package documented here https://godoc.org/github.com/coreos/go-oidc

In terms of v1 client concurrency, it isn't intended to be used anymore, so any thread safety is whatever the code does. I would strongly recommend using the v2 branch instead.

Closing for now since this is a question and I prefer to use the issue tracker for bugs and feature requests.
