### ISSUE TITLE
Handle Grant type - client credential - Example request

### ISSUE THREAD

**Issue by soamyak** [coreos/go-oidc#208]
I am using keycloak for server authentication which is hosted at internal server. 

                oauth2Config := oauth2.Config{
		ClientID:     test-data,
		ClientSecret: "ewerereoekdkggf",
		RedirectURL:  "http://localhost:5000/v1.0",
		Scopes:       []string{"all"},

		Endpoint: oauth2.Endpoint{
			AuthURL:  "https://keycloakt.iservice.companydomain.com/auth/realms/i-service/protocol/openid-connect/auth",
			TokenURL: "https://keycloakt.iservice.companydomain.com/auth/realms/i-service/protocol/openid-connect/token",
			
		},
	}
To handle the request at client side, I have implemented http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) and http.HandleFunc("/v1.0", func(w http.ResponseWriter, r *http.Request) as discribed in - 

https://stackoverflow.com/questions/48855122/keycloak-adaptor-for-golang-application.

My API listen and server at localhost  5000 and I am using POSTMAN to test the authentication. 

Issue - 
Call to below API
GET - http://localhost:5000/v1.0/testplans/2019-07-15T17:00:01.000ZZ 

Is generating a positive response , irrespective of correct or incorrect access token in the Header of request.  I do not get redirected to any authorization page. What is the catch here?

**Comment by ericchiang** [comment]
Hi, this looks like an issue with golang.org/x/oauth2, not this package. You might want to ask on golang-nuts (https://github.com/golang/go/wiki/Questions), or with the Keycloak community, but honestly I'm not sure what you're trying to do. Providing a complete program would go a long way.

Either way I'm closing this issue since it's not related to go-oidc.
