### ISSUE TITLE
Verify `id_token` and `access_token` already obtained from oidc-client-js?

### ISSUE THREAD

**Issue by sheeeng** [coreos/go-oidc#311]
How to verify both `id_token` and `access_token` already obtained from [oidc-client-js](https://github.com/IdentityModel/oidc-client-js/wiki#user) using this golang library?

For example, both `id_token` and `access_token` needs to be verified inside the golang backend before an API is executed.

**Comment by ericchiang** [comment]
The API you're looking for is https://pkg.go.dev/github.com/coreos/go-oidc/v3/oidc#IDTokenVerifier.Verify

If you would like to prove the access token was issued for the same ID Token, and your provider includes the at_hash claim, you can use https://pkg.go.dev/github.com/coreos/go-oidc/v3/oidc#IDToken.VerifyAccessToken

Otherwise, access tokens aren't generally verified by the client.

Closing since this isn't a bug. Please let me know if any of the documentation could improve
