### ISSUE TITLE
RemoteKeySet should re-query discovery

### ISSUE THREAD

**Issue by jordaniversen** [coreos/go-oidc#332]
Hello,
Curious as to whether there is support for configuring how the JSON Web Keys are cached.  It seems like the only support is via the "cache-control" response header when getting the JWKS.  Would it be possible to add such functionality?  Ex. "cache for 12 hours".

**Comment by ericchiang** [comment]
The v3 branch actually ignores the cache-control header and refreshes when it sees a key ID it doesn't have cached, as recommended by the spec:

https://github.com/coreos/go-oidc/blob/6ce86d9e30589a68cbf891b7c4fc0d316201b786/oidc/jwks.go#L114-L117

Is that an alternative that works for you? Are you seeing issues with that strategy?

We could add something to the RemoteKeySet that lets you do more elaborate caching logic if you really need something custom. But interested what the use case is.

https://pkg.go.dev/github.com/coreos/go-oidc/v3/oidc#RemoteKeySet

**Comment by jordaniversen** [comment]
Hi Eric,

Thanks for the quick reply.  I noticed that it wasn't used in the code also
in v3, I assumed I was misunderstanding something ;)

Our requirement is to simply refresh every 12 hours.  Is it possible for a
key to be updated but reuse the same kid?  Or is that prevented according
to a spec?

Thanks

**Comment by ericchiang** [comment]
Different keys should definitely have different "kid" values :) https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.4

This shouldn't be too hard to add, but can you elaborate on why this is a requirement? E.g.
- Is it a security concern? If it can't refresh its cache, should it start rejecting ID tokens?
- Is this an issue with a provider that's updating the keys but not changing the "kid"?

**Comment by jordaniversen** [comment]
I guess I'm just unsure of how long the discovery document should be cached.  And then rely on the logic that you pointed to (automatic refreshing of the keys from the previously-defined jwks_uri).  But my concern was simply what if the discovery document was changed and the jwks_uri is now different.  I was hoping there was some guidance in some spec, but perhaps there isn't.

So perhaps I can assume every 12 hours I should update the discovery document.  I guess this essentially means that I would use my instance of `oidc.NewProvider` for 12 hours, and then create a new instance by calling `oidc.NewProvider` again every 24 hours.  Or would there be a better way in this library?

**Comment by ericchiang** [comment]
Ah. Currently this package doesn't handle refreshes of the discovery document. Every provider I've worked with might change it over the longer term (e.g. once a year), but always supports rotation by hitting the same jwks_uri to get new keys.

RemoteKeySet currently doesn't consider jwks_uri changes. Particularly because we need to support providers that don't support discovery https://pkg.go.dev/github.com/coreos/go-oidc/v3/oidc#NewRemoteKeySet

Having a verifier that needs to consider updates of both the discovery document and jwks_uri isn't something I'm thrilled about handling unless there's a strong use case. Have you hit issues with providers? Or is this a hypothetical concern?

**Comment by jordaniversen** [comment]
> Have you hit issues with providers? Or is this a hypothetical concern?
This would be a hypothetical concern.  What about allowing a configuration of refreshing just the (previously fetched) JWKS URI?  In addition to fetching it when a "kid" is not found?  Again perhaps that may be something against the spec.

**Comment by ericchiang** [comment]
Updated title based on what I think this is asking :)

If this is just hypothetical, I'm inclined not to do anything. Again, we'd likely need to rework the API since you can create a remote key set from just a JWKS URI and not a provider directly. It's also not clear how often we'd refresh the discovery document. I'm not thrilled about adding cache-control logic again, since providers implement it in all sorts of weird ways.

Closing for now, since it's hypothetical. If this impacts a real provider, feel free to comment or reopen!
