### ISSUE TITLE
Add device flow authorization support

### ISSUE THREAD

**Issue by sealbro** [coreos/go-oidc#357]
Hi, guys!

What do you think about supporting [device flow ](https://curity.io/resources/learn/oauth-device-flow/) authorization?

Configuration `.well-known/openid-configuration` contains `device_authorization_endpoint`
like {{KEYCLOAK_URL}}/realms/{{KEYCLOAK_REALM}}/protocol/openid-connect/auth/device

I think adding URL into `providerJSON/Provider` and a method like [here](https://github.com/rjw57/oauth2device/blob/master/oauth2device.go#L86) for waiting for token

**Comment by ericchiang** [comment]
Hey!

The spec you're referring to (https://www.rfc-editor.org/rfc/rfc8628.html) is an OAuth 2.0 specification. It's not related to OpenID Connect (https://openid.net/developers/specs/).

This issue is likely better for Go's oauth2 repo: https://github.com/golang/oauth2

Going to close out since go-oidc is focused on OpenID Connect, not OAuth 2.0. But please re-open if I've misunderstood.

**Comment by sealbro** [comment]
Ok, thanks!
Issue [here](https://github.com/golang/oauth2/issues/418)
