### ISSUE TITLE
using http instead of https?

### ISSUE THREAD

**Issue by tamis-laan** [coreos/go-oidc#386]
I'm using keycloak for authentication and I'm trying to connect internally within my cluster over http:
``` go
provider, err := oidc.NewProvider(context.Background(), "http://keycloak-service:8080/realms/test/") 
```
However this results in:
```
oidc: issuer did not match the issuer returned by provider, expected "http://keycloak-service:8080/realms/test/" got "https://keycloak-service:8080/realms/test"
```
Looks like go-oidc is enforcing https.

**Comment by ericchiang** [comment]
Issuer values are expected to match identically. "http://example.com" is a different issuer than "https://example.com", which is what the error message is saying. go-oidc doesn't have any logic to inspect the protocol

This matters because the ID token issuer also needs to match identically. Id recommend:
* reconfiguring your keycloak server to use http for the issuer
* connect over https
* use one of the options in this package to specify the issuer manually.

Hope this helps. Closing out since we're correctly reporting a misconfiguration

**Comment by tamis-laan** [comment]
@ericchiang "use one of the options in this package to specify the issuer manually" how would I be able to do this? Do you have a small example?
