### ISSUE TITLE
oidc: floating point values in claims don't interop well with certain OIDC implementations

### ISSUE THREAD

**Issue by fnordahl** [coreos/go-oidc#55]
According to the [OpenID Connect specification section 2. ID Token](http://openid.net/specs/openid-connect-core-1_0.html#IDToken) the ``exp`` and ``iat`` claims are REQUIRED and specified as JSON number representing the number of seconds from 1970-01-01T0:0:0Z.

The current implementation converts the timestamps from golang Time, to Unix int64 and then finally converts that to a float64. When doing this the numbers come across as ``1.456478332e+09`` instead of ``1456478332``.

Other implementations, like mod_auth_openidc for Apache used by among others OpenStack, does not understand Unix timestamps represented as 64-bit floating point numbers.

I would argue that it breaks the spec by using float64, even though it does not explicitly say "integer" rathern than just JSON numbers.

Is there any reason for why the 64-bit integers are converted to 64-bit floating point numbers?

**Comment by bobbyrullo** [comment]
We're not breaking the spec by using floats - all JSON numbers are floats. The other implementations are using broken JSON parsers I guess.

 That being said, I don't know why we're doing this conversion - any ideas @sym3tri or @bcwaldon ?

**Comment by fnordahl** [comment]
@bobbyrullo the mod_auth_openidc implementation explicitly checks for integer values. I guess that is wrong in some sense, but looking at the JSON-examples in the spec I can't blame them for doing so. :-)

The wording of the definition for NumericDate in [RFC 7519](https://tools.ietf.org/html/rfc7519) suggests integer or formatted textual representation.

**Comment by bobbyrullo** [comment]
According to that definition, it can't be a formatted textual representation, and it can contain floats (see bolded sections)

> NumericDate
>       A JSON **numeric value** representing the number of seconds from
>       1970-01-01T00:00:00Z UTC until the specified UTC date/time,
>       ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
>       2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
>       which each day is accounted for by exactly 86400 seconds, other
>       than that **non-integer values can be represented**.  See RFC 3339
>       [RFC3339] for details regarding date/times in general and UTC in
>       particular.

In the spirt of "be liberal in what you accept and conservative in what you send" we could do the following: 

a) When creating a NewClaim() round to the second, and encode as Int
b) When decoding claims, continue to interpret and store as float, so that information in claims from other places is not lost. We should probably also fix [TimeClaim](https://github.com/coreos/go-oidc/blob/master/jose/claims.go#L73) then, so that it doesn't round to int.

@gtank - Security implications of only creating times to the second here?

**Comment by gtank** [comment]
@bobbyrullo I can't think of any problems here.
